baseURL = "https://SeungHyeokJeon.github.io/"
title = "블로그제목"

languageCode = "kr-ko"
DefaultContentLanguage = "kr"
theme = "hugo-hello-programmer-theme"
# disqusShortname = "개별설정"
# googleAnalytics = "개별설정"
paginate = 7

[author]
    name = "이름"
    email = "이메일"

[params]
    description = "블로그 설명"