baseURL = "https://SeungHyeokJeon.github.io/"
title = "여기는 블로그입니다."

languageCode = "kr-ko"
DefaultContentLanguage = "kr"
theme = "hugo-hello-programmer-theme"
# disqusShortname = "개별설정"
# googleAnalytics = "개별설정"
paginate = 7

[author]
    name = "SeungHyeok Jeon"
    email = "sdkazx2717@gmail.com"

[params]
    description = "개발 공부 관련 포스트를 업로드하는 블로그입니다."